// External Dependancies
const mongoose = require('mongoose');

const custodianSchema = new mongoose.Schema({
  id: mongoose.Schema.Types.ObjectId,
  startTime: Date,
  dayOfWeek:Number,
  isWeekday:Boolean,
  isWeekend:Boolean,
  caloriesBurned:Number,
  caloriesBMR:Number,
  stepsDistance:Number,
  Elevation:Number,
  restingHeartRate:Number,
  floors:Number,
  Minutessedentary:Number,
  MinuteslightlyActive:Number,
  MinutesFairlyActive:Number,
  MinutesVeryActive:Number,
  ActivityCalories:Number,
  ActiveScore:Number,
  CardioMinutes:Number,
  Cardiocalories:Number,
  FatBurnminutes:Number,
  FatBurncalories:Number,
  Peakminutes:Number,
  Peakcalories:Number,
  NormalCardiocalories:Number,
  NormalCardiominutes:Number,
  SleepEfficiency:Number,
  MinutesAsleep:Number,
  Minutestofallasleep:Number,
  SleepStarttime:Date,
  SleepEndtime:Date,
  Timeinbed:Number,
  minutesDeepsleep:Number,
  Deepsleepcount:Number,
  MinutesLightsleep:Number,
  lightSleepCount:Number,
  minutesREMsleep:Number,
  REMsleepcount:Number,
  minutesAwake:Number,
  minutesAwakeCount:Number,
  Deepsleep:Number,
  Lightsleep:Number,
  REMsleep:Number
});

module.exports = mongoose.model('Custodian', custodianSchema);
