http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  agreements:
    host: localhost
    paths: ['/agreements/register', '/agreements/*']
serviceEndpoints:
  agreements:
    url: 'http://localhost:3000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  agreements:
    apiEndpoints:
      - agreements
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: agreements
              changeOrigin: true
